### ISSUE TITLE
Azapi_update_resource - Create when not exists 

### ISSUE THREAD

**Issue by mlomat** [Azure/terraform-provider-azapi#165]
Hello team, 
I have a problem, because I want to trigger Run on Automation Account Runbook. 
Rest Api is not supporting delete command, so my code is working for first deployment, but later it's failing, because terraform is sending delete to REST API. AzApi_update_resource is not working, because it's failing with Not found job... because job is not there yet. Is there a way to have flag "provision_if_first_time" or something which will create resource if it does not exist? Or do you have any workaround for this? Because API is creating a new object each time when you call it...
```
resource "azapi_resource" "master_start" {
  type = "Microsoft.Automation/automationAccounts/jobs@2019-06-01"
  name = uuid()
  parent_id = var.automation_account_id
  body = jsonencode({
    properties = {
      parameters = {}
      runbook = {
        name = "TestRunbook"
      }
      runOn = ""
    }
  })
```

**Comment by ms-henglu** [comment]
Hi @mlomat ,

Thank you for opening this issue!

Resources that doesn't support full CRUD should not be managed by `azapi_resource`. I have some workarounds for this case:

1. Use `azapi_resource` to manage it. But when you want to remove it from configuration, you must run `terraform state rm azapi_resource.job` which isn't ideal.

2. Use the new operation resource, which isn't released yet but soon. It can be used to perform any azure resource operation, so we can use it to create a job resource. More details: https://github.com/Azure/terraform-provider-azapi/issues/57

Lastly, it's not recommended to use `uuid` function directly in resource arguments, because it will result in spurious diffs. 
https://www.terraform.io/language/functions/uuid#uuid-function

**Comment by mlomat** [comment]
HI @ms-henglu 

1. Yep, I did exactly that, but it's not a workaround for automated pipeline, because in this case I will need to do this always before apply. It's always a new object, because API require new GUIDs, so I cannot reuse the same.
2. Awesome ! 🥇 

Regarding uuid - Yep, I know, it's just some dirty code example, but thanks! 

Best
Mateusz

**Comment by ms-henglu** [comment]
Hi @mlomat ,

The [azapi_resource_action](https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_resource_action) has been released in azapi 0.5.0, would you please give it a try? And there's an example to list tables under an LA workspace.
https://github.com/Azure/terraform-provider-azapi/blob/f9c339ce179b52f63b4f6725ae74e5b46a490be7/examples/Microsoft.Automation/trigger_jobs/main.tf

**Comment by mlomat** [comment]
Hi, 
I tested it. Looks good and working as expected. I will only change your example to similar use as it is on Azure Portal. So to use guid as a name instead of name of the job. You need to have something which will trigger it in case of some changes on source. I am counting MD5 of runbook file, to figure out if it changed. 

Best
Mateusz

```
resource "random_uuid" "trigger_master_job" {
  keepers = {
    gitchanges = md5(local.gitsyncBody)
  }
}


resource "azapi_resource_action" "master_start" {
  type        = "Microsoft.Automation/automationAccounts/jobs@2019-06-01"
  resource_id = "${var.automation_account_id}/jobs/${random_uuid.trigger_master_job.id}"
  method      = "PUT"
  body = jsonencode({
    properties = {
      runbook = {
        name = "testRunbook"
      }
      runOn = ""
    }
  })

  depends_on = [
    null_resource.trigger_sync_runbooks
  ]

}

```

**Comment by ms-henglu** [comment]
@mlomat - Thanks for the example! It looks great!
