### ISSUE TITLE
Import not using specified api-version

### ISSUE THREAD

**Issue by Tbohunek** [Azure/terraform-provider-azapi#174]
Why does the `terraform import` command require explicit `?api-version=xzy` if there's already version specified in resource's `type`?
```
resource "azapi_resource" "dns_resolver" {
  type = "Microsoft.Network/dnsResolvers@2020-04-01-preview"
}
```

> terraform import azapi_resource.dns_resolver /subscriptions/sss.../resolver
│
azapi_resource.dns_resolver: Refreshing state... [id=/sss.../resover]
│ Error: reading "Resource: (ResourceId \"/sss.../resolver\" / Api Version \"2022-07-01\")": GET https://management.azure.com/subscriptions/sss.../resolver
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: NoRegisteredProviderFound
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "NoRegisteredProviderFound",
│     "message": "No registered resource provider found for location 'westeurope' and API version '2022-07-01' for type 'dnsResolvers'. The supported api-versions are '2020-04-01-preview'. The supported locations are 'westcentralus, eastus2, westeurope, northeurope, australiaeast, uksouth, southcentralus, eastus, northcentralus, westus2, westus3'."
│   }
│ }

**Comment by ms-henglu** [comment]
Hi @Tbohunek ,

Thank you for taking time to report this issue!

The feature allows user to import resource without api-version has been supported in v0.4.0, https://github.com/Azure/terraform-provider-azapi/issues/119. It will use the latest api-version by default, but it couldn't use the type specified in the config when import, because unfortunately provider is not allowed to access config during importing.

More info can be found [here](https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_resource#import).

**Comment by Tbohunek** [comment]
A really weird limitation, but thanks for clarification.
