### ISSUE TITLE
azapi_resource dynamic blocks

### ISSUE THREAD

**Issue by mpjtaylor** [Azure/terraform-provider-azapi#335]
Im trying to use "Microsoft.Compute/virtualMachines@2023-03-01" but it wants to constantly add and i only use this sometimes anyway is there a way to dynamically add a block?

  capacityReservation = {
    capacityReservationGroup = {
      id = tostring(local.virtual_machine_rehosted_capacity_group)
    }
  }

I also see issues with false and "false" causing an update.

**Comment by ms-henglu** [comment]
Hi @mpjtaylor ,

Thank you for taking time to report this issue!

It's recommended to use `jsonencode` function to construct the JSON for the `body` field. Because this function takes an HCL object, and returns a valid JSON string. Since it's an HCL object, we could use the [conditional expressions](https://developer.hashicorp.com/terraform/language/expressions/conditionals):

```hcl
      capacityReservation = local.virtual_machine_rehosted_capacity_group != "" ? {
        capacityReservationGroup = {
          id = local.virtual_machine_rehosted_capacity_group
        }
      } : null

```

**Comment by ms-henglu** [comment]
I'll close this issue as it's resolved but feel free to reopen it if there's any question.
