### ISSUE TITLE
`use_msi` defaults to `true` by design?

### ISSUE THREAD

**Issue by tamirkamara** [Azure/terraform-provider-azapi#377]
Hi,
I tried to review the original PR and didn't find a discussion around the default value of `true` for `use_msi`.
I think it is worth a discussion because this changes the behavior for all existing use-cases that rely on the older default=false. Another point is the default is the opposite in the `azurerm` provider.

Is it worth to consider aligning to a `false` default?

**Comment by ms-henglu** [comment]
Hi @tamirkamara ,

Thank you for taking time to report this issue and apologize for late response!

Yes, the default behavior is different from `azurerm` provider because when introduce this field, we don't want to introduce any breaking changes. And we'll consider aligning the behavior with the `azurerm` provider in the next major version.

Thanks!

**Comment by tamirkamara** [comment]
Hi @ms-henglu 
I don't understand because when you introduced this field you indeed introduced a breaking change - the provider didn't have support for MSI before so the default should have been false but by making it true you changed the behavior for all existing use cases.

**Comment by ms-henglu** [comment]
Sorry for late response. The `use_msi` is introduced in v1.7.0 and in v1.6.0 the managed identity authentication is already part of the default authentication flow. 

To align with azurerm provider, in the next major version, we'll change the default value of `use_msi` to false.

**Comment by ms-henglu** [comment]
Close this issue as completed via https://github.com/Azure/terraform-provider-azapi/pull/596. Feel free to reopen it if there's any questions.
