### ISSUE TITLE
Feature request: EventHub SchemaGroup Schema dataplane resource 

### ISSUE THREAD

**Issue by cveld** [Azure/terraform-provider-azapi#415]
I believe it is currently not provided by azapi version 1.12 to provision a schema to a eventhub schemagroup.

The data plane url is as follows:
https://mynamespace.servicebus.windows.net/$schemagroups/mygroup/schemas/schemaname?api-version=2022-10

**Comment by ms-henglu** [comment]
Hi @cveld ,

Thank you for taking time to report this issue and apologize for late response.

Unfortunately we couldn't support this API in `azapi` provider, because there's no APIs to read/delete the schema resource, only an API to create one.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/schemaregistry/data-plane/Microsoft.SchemaRegistry/stable/2021-10/schemaregistry.json#L187

I'll close this issue but feel free to reopen if there's any questions.

**Comment by mgnisia** [comment]
Hi @ms-henglu are there any plans to implement this in the future? How do you suggest to solve this issue?

**Comment by stemaMSFT** [comment]
@mgnisia data plane URL's are inherently dependent on the design of the API for us to be able to support. Without proper CRUD operations (read/delete) then this resource cannot be supported in a way that resembles expected Terraform behavior. So there's no real ETA, a request would need to be created against the API/service owners.

**Comment by mgnisia** [comment]
Thanks for the fast reply! 😊
