### ISSUE TITLE
Environment variable for "enable_hcl_output_for_data_source"

### ISSUE THREAD

**Issue by cwe1ss** [Azure/terraform-provider-azapi#516]
It would be great if we could set the provider flag `enable_hcl_output_for_data_source` via an environment variable. This would make it more consistent with other fields like `skip_provider_registration`, which can be set via the environment variable `ARM_SKIP_PROVIDER_REGISTRATION `.

**Comment by ms-henglu** [comment]
Hi @cwe1ss ,

Thank you so much for taking time to report this issue and apologize for late response.

The `enable_hcl_output_for_data_source` is introduced as a workaround to mitigate the breaking change introduced in v1.13.0. And this field will be removed in the next major release because the HCL format will be the default output format.

I'll close this issue as resolved, but feel free to reopen it if there's any question.
